FROM python:3.10-slim

WORKDIR /app

# Copier les dependances
COPY requirements.txt .

# Installer les librairies
RUN pip install --no-cache-dir \
    pandas \
    openpyxl \
    mysql-connector-python \
    sqlalchemy \
    streamlit \
    plotly \
    folium \
    streamlit-folium \
    python-dotenv

# Copier le code
COPY dashboard/ ./dashboard/
COPY data/ ./data/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]