FROM apache/airflow:2.8.2

# Installer les dependances Python necessaires pour le pipeline
RUN pip install --no-cache-dir \
    openpyxl==3.1.2 \
    mysql-connector-python==8.3.0 \
    python-dotenv==1.0.1 \
    folium==0.16.0