FROM python:3.10-slim

WORKDIR /app

COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir --timeout=120 -r requirements.streamlit.txt

COPY dashboard/ ./dashboard/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]

